version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: alumnos
      POSTGRES_USER: root
      POSTGRES_PASSWORD: tlTaGftauvitqVwh9z5GB1mBPb1JjtlK
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  alumnos-backend:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/alumnos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tlTaGftauvitqVwh9z5GB1mBPb1JjtlK
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
